name: Butterfly

packages:
  - "*"

scripts:
  format:
    exec: flutter format .
  check-format:
    exec: flutter format --set-exit-if-changed .
  analyze:
    exec: flutter analyze .
  test:
    exec: flutter test