on: push
name: CI
jobs:
  check-app:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3
      # setup java
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      # flutter action
      - uses: subosito/flutter-action@v2
      # activate melos
      - name: Activate melos
        run: dart pub global activate melos
      # check format
      - name: Check format
        run: melos run check-format
      # analyze
      - name: Analyze
        run: melos run analyze
      # test
      - name: Test
        run: melos run test
  build-server:
    needs: check-app
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3
      # setup dart
      - uses: cedx/setup-dart@v3
      # build
      - name: Build server
        run: |
          dart pub global activate dart_frog_cli
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          cd butterfly_back
          dart_frog build
  build-app:
    needs: check-app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetBuild: [appbundle, web]
    steps:
      # checkout
      - uses: actions/checkout@v3
      # setup java
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      # flutter action
      - uses: subosito/flutter-action@v2
      # build
      - name: Build front
        run: |
          cd butterfly_front
          flutter build ${{ matrix.targetBuild }}